---
- name: Install Apache2 and setup homepage
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: true

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Create index.html with homepage content
      copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>New Era Solutions Academy</title>
          </head>
          <body>
              <h1>Welcome to New Era Solutions Academy. This is class 19</h1>
          </body>
          </html>
      notify: Restart Apache

    - name: Ensure the firewall allows HTTP traffic (optional)
      ufw:
        rule: allow
        port: 80
        proto: tcp

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
